### ISSUE TITLE
No support for SCP03 AES 192 or 256 bit keys

### ISSUE THREAD

**Issue by dmercer-google** [kaoh/globalplatform#31]
The keys are hardcoded to be 16 bytes long everywhere.

**Comment by kaoh** [comment]
Which cards are supporting 192 or 256 bits? Do you have samples for testing?

**Comment by dmercer-google** [comment]
> Which cards are supporting 192 or 256 bits? Do you have samples for testing?

The card I am using is the Infineon Secora ID S SLJ52GDT120CS.  Unfortunately I cannot give you one but I have spoken to Infineon and they are happy to provide you with what you need.

Please send me an email and I will give you the contact details of the correct person to talk to.

You can email me by replacing the "-" in my Github username with an "@" and add dot com to the end.

**Comment by koh-osug** [comment]
So far no further response from Infineon after the initial call. I have triggered them again today.

**Comment by koh-osug** [comment]
I have the samples. I will investigate this now and try to add support.

**Comment by kaoh** [comment]
Validated with the test cards under this branch: https://github.com/kaoh/globalplatform/tree/scp03_aes192_and_aes256

Please check it out.

**Comment by dmercer-google** [comment]
Looks to be resolved
