### ISSUE TITLE
Is extended APDU command supported ? 

### ISSUE THREAD

**Issue by proga7med** [kaoh/globalplatform#53]
Is global platform supported a extended APDU command ? Because I have a case which is sending a apdu command to applet and the command size is 286 bytes. And I cannot see any indication for that.

**Comment by kaoh** [comment]
The [PC/SC  plugin](https://github.com/kaoh/globalplatform/blob/master/gppcscconnectionplugin/src/gppcscconnectionplugin.c) should support it. I rememember to have removed any 255 bytes sending limitation, but I had no card or applet for testing this. The only function supporting this should be [GP211_send_APDU](https://github.com/kaoh/globalplatform/blob/master/globalplatform/src/globalplatform.c#L641). You can give it a try. All functions related to the GlobalPlatform specification might not support it. I'm not even sure if GlobalPlatform support extended APDUs.
If you are usign GPShell, then the command [`send_apdu`](https://github.com/kaoh/globalplatform/blob/master/gpshell/src/gpshell.c#L2032) with no security can be used. It defines a maximum of 65535 bytes for [sending APDUs](https://github.com/kaoh/globalplatform/blob/master/gpshell/src/gpshell.c#L62). If it does not work please mention the card you are using a test applet would also be handy.
