### ISSUE TITLE
SCP10

### ISSUE THREAD

**Issue by Armellys** [kaoh/globalplatform#72]
Hi o/ 

I am new with globalplatform and I want to have an encrypted communication between my applet (on card) and my off card device.
I was reading the gp specification about secure communication and understood that there are 2 possibility : 
- symmetric encryption (protocol SCP01, SCP02 and SCP03)
- asymmetric encryption (protocol SCP10)

I would rather go for asymmetric encryption but I do not find an implementation of it.
Is adding SCP10 in the roadmap of your project ?

Otherwise I think I'll try to do it myself but don't really know where to start for now.

**Comment by koh-osug** [comment]
Sorry, I missed this. No it is not on the road map. I'm also not aware of any card supporting this. If you find a card, then it might be interesting, otherwise not.
