### ISSUE TITLE
put key with parameter key type

### ISSUE THREAD

**Issue by yp25** [kaoh/globalplatform#73]
is there any available parameter options for passing key type (for example "DES" 0x80 or "AES" 0x88 ) on put_sc_key command ?

I have java card with default SCP02-i55, after enable secure channel protocol to support both SCP02 and SCP03, I need to add the new key for SCP03 (with new key version = 0x30 --> refer to the chip preperso administration document, 0x30 means AES key) . I open the SCP02 communication and try to use this command to add key with key version 48. 
`put_sc_key -keyver 0 -newkeyver 48 -mac_key 404142434445464748494a4b4c4d4e4e -enc_key 404142434445464748494a4b4c4d4e4e -kek_key 404142434445464748494a4b4c4d4e4e`
and got error 6A80. 

when I add DES key with different key version 0x20 --> 0x20 means DES key), the put_sc_key command works. So I believe the error occurred because the key type should be AES, not DES.

From globalplatform.c source code, function put_secure_channel_keys,  the key type  set to the default value like this :

`

> if (cardInfo.specVersion == OP_201) {
> 		keyType = OP201_KEY_TYPE_DES_ECB;
> 	}
> 	else {
> 		keyType = GP211_KEY_TYPE_DES;
> 	}
> 	if (secInfo->secureChannelProtocol == GP211_SCP03) {
> 		keyType = GP211_KEY_TYPE_AES;
> 	}

`

is it possible to add new feature to enable passing key type parameter ? Thank you Mr. @kaoh

**Comment by koh-osug** [comment]
Right now like you analyzed it correctly, the key type is fixed. I will  try to add this feature to the road map. Please try this in the meanwhile:

> open_sc  -scp 3 <other params>

This sets SCP03 explicitly and should then use an AES key. Or is the key you are adding the initial SCP03 key which has to be stored with SCP02?
 
See [gpshell.1.md](https://github.com/kaoh/globalplatform/blob/master/gpshell/src/gpshell.1.md)

**Comment by yp25** [comment]
>  Or is the key you are adding the initial SCP03 key which has to be stored with SCP02?
yes. open communication with SCP02, then add SCP03 key.

btw I try to modify the source code to test keytype 0x88 / 136 . but got response 6982. 
`put_sc_key -keytype 136 -keyver 0 -newkeyver 48 -mac_key B70E2A9F15335C0FE7A8B15A9F2C6266 -enc_key FB818CB44F35D5BEC3038234D0AC015C -kek_key 7B73940892323802F3A95601F797BEB5
Key Type 0x88 
Command --> 80D80081433088100062F72B614E754E841D3B18C07D503303B90A6788102DAE2614F38C384EA1A932A960D3A6E40384A6068810DAD165FBACD4EF1FC56D9B5EE084D598032B243600
Wrapped command --> 80D80081433088100062F72B614E754E841D3B18C07D503303B90A6788102DAE2614F38C384EA1A932A960D3A6E40384A6068810DAD165FBACD4EF1FC56D9B5EE084D598032B243600
Response <-- 6982`

**Comment by koh-osug** [comment]
Have you patched gpshell and the globalplatform library to accept the key type as parameter? As simple test you could also hard code the key type in the function `put_secure_channel_keys` to see if it works. Has JCShell an option to see the send data in plain? I think the data is already encrypted. If you could see the plain data, we would see which identifier for the key type works.

**Comment by koh-osug** [comment]
I created a stub to support this:

https://github.com/kaoh/globalplatform/tree/put_sc_with_key_type

This is untested, but maybe it works directly. The new option is called "keyType" and the type is passed as hex string, e.g. 88 for AES.

**Comment by yp25** [comment]
> Have you patched gpshell and the globalplatform library to accept the key type as parameter? As simple test you could also hard code the key type in the function `put_secure_channel_keys` to see if it works. 

Yes. already patched gpshell and globalplaform library to accept the key type as parameter. mine using '-keytype' with decimal number, and yours '-keyType' with hexadecimal number . from the log, the key type is correct. tried to hard code the key type and still got same error. I tried your latest code "put_sc_with_key_type" and also got same error when put_sc_key with keyType AES


```
this one is new DES key with newkeyversion 0x20 / 32 decimal  :

put_sc_key -keyType 80 -keyver 0 -newkeyver 32 -mac_key 404142434445464748494A4B4C4D4E4F -enc_key 404142434445464748494A4B4C4D4E4F -kek_key 404142434445464748494A4B4C4D4E4F
Command --> 80D80081432080102FD3E7126616DBFDE95BB87AEAADAB18038BAF4780102FD3E7126616DBFDE95BB87AEAADAB18038BAF4780102FD3E7126616DBFDE95BB87AEAADAB18038BAF4700
Wrapped command --> 80D80081432080102FD3E7126616DBFDE95BB87AEAADAB18038BAF4780102FD3E7126616DBFDE95BB87AEAADAB18038BAF4780102FD3E7126616DBFDE95BB87AEAADAB18038BAF4700
Response <-- 208BAF478BAF478BAF479000
Unwrapped response <-- 208BAF478BAF478BAF479000
command time: 188 ms

and this one is new AES key with newkeyversion 0x30 / 48 decimal :

put_sc_key -keyType 88 -keyver 0 -newkeyver 48 -mac_key 404142434445464748494A4B4C4D4E4F -enc_key 404142434445464748494A4B4C4D4E4F -kek_key 404142434445464748494A4B4C4D4E4F
Command --> 80D80081433088102FD3E7126616DBFDE95BB87AEAADAB18038BAF4788102FD3E7126616DBFDE95BB87AEAADAB18038BAF4788102FD3E7126616DBFDE95BB87AEAADAB18038BAF4700
Wrapped command --> 80D80081433088102FD3E7126616DBFDE95BB87AEAADAB18038BAF4788102FD3E7126616DBFDE95BB87AEAADAB18038BAF4788102FD3E7126616DBFDE95BB87AEAADAB18038BAF4700
Response <-- 6982
Unwrapped response <-- 6982
put_secure_channel_keys() returns 0x80206982 (6982: Command not allowed - Security status not satisfied.)

```

> Has JCShell an option to see the send data in plain? I think the data is already encrypted. If you could see the plain data, we would see which identifier for the key type works.

will try to find out. Thank you for your help Mr. @koh-osug

**Comment by yp25** [comment]
from JCShell log, I try to figure it out : 
1. open communication (init update & ext auth) SCP02
2.  put sc key with key type AES (0x88), new ENC/MAC/DEK key = 404142434445464748494A4B4C4D4E4F , session DEK key = C61DF24D2C9A770E32E969984B5B7074, new key version = 0x30
3. the command apdu = 80D800814630881110B23034FA4329DE9AD8E91583618813B303504A77881110B23034FA4329DE9AD8E91583618813B303504A77881110B23034FA4329DE9AD8E91583618813B303504A7700

CLA INS P1 P2 => 80D80081
LC => 46
Data => 
30 --> key version
88 11 10 B23034FA4329DE9AD8E91583618813B303 504A77
88 11 10 B23034FA4329DE9AD8E91583618813B303 504A77
88 11 10 B23034FA4329DE9AD8E91583618813B303 504A77
LE = 00

 (88= AES; 11 = 10+1 ? (don't know where it come from); 10 = key length; key data = new ENC key encrypted using 3DES ECB with key = session DEK key; key check value using AES GPC 2.2.1 Amendment D 7.2.2)

B23034FA4329DE9AD8E91583618813B303 = output from encrypt 3DES ECB, key = C61DF24D2C9A770E32E969984B5B7074, data input = 404142434445464748494A4B4C4D4E4F 

key check value AES = 504A77 = first 3 byte from encrypt AES CBC with key = new ENC key = 404142434445464748494A4B4C4D4E4F, data input = 01010101010101010101010101010101. output = 504A77E6E457DD861E066F7804281A5F

try to find other reference from [GPSession.java - encodeKey](https://github.com/martinpaljak/GlobalPlatformPro/blob/master/library/src/main/java/pro/javacard/gp/GPSession.java#L855)
and [GPCrypto.java - kcv_aes](https://github.com/martinpaljak/GlobalPlatformPro/blob/master/library/src/main/java/pro/javacard/gp/GPCrypto.java#L216)
and [GPCrypto.java - one_bytes_16](https://github.com/martinpaljak/GlobalPlatformPro/blob/master/library/src/main/java/pro/javacard/gp/GPCrypto.java#L54)

seems that need to check and modify the function of [calculate_key_check_value](https://github.com/kaoh/globalplatform/blob/master/globalplatform/src/crypto.c#L1363)

**Comment by koh-osug** [comment]
I have already added keys successfully. The 0x11 should be already be set with `encrypted_key_length + 1`:

~~~
	keyDataField[i++] = keyType;
	if (isSensitive) {
		status = encrypt_sensitive_data(secInfo, keyData, keyDataLength, encrypted_key, &encrypted_key_length);
		if (OPGP_ERROR_CHECK(status)) {
			goto end;
		}
		if (encrypted_key_length != keyDataLength || secInfo->secureChannelProtocol == GP211_SCP03) {
			// + 1 byte key component length field
			keyDataField[i++] = encrypted_key_length + 1;
			keyDataField[i++] = keyDataLength;
~~~

Can you please check if the JCShell output differs from gpshell (expect the different encrypted data because of the session key)?

**Comment by yp25** [comment]
>I have already added keys successfully

how you did it ? Can I request a copy of the complete logs starting from open_sc ?

I did a little modification in  [get_key_data_field](https://github.com/kaoh/globalplatform/blob/master/globalplatform/src/crypto.c#L1407)   function --> add || keyType == GP211_KEY_TYPE_AES, because the current SCP is SCP02, not SCP03 (secInfo->secureChannelProtocol => GP211_SCP02), so with your original code need to modified like this :

	if (secInfo->secureChannelProtocol == GP211_SCP03  || keyType == GP211_KEY_TYPE_AES ) {
		// the length of the key component is always included
		sizeNeeded++;
	}
but this caused problem with line 1415 , because sizeNeed > *keyDataFieldLength. 
sizeNeed should be = key type (1 byte) + encrypted_key_length + 1( 1 byte) + encrypted_key_length (1byte) + key data (16 bytes) + length_key_check_value (1 bytes) + key check value (3 bytes) ==> 1+1+1+16+1+3 => 23. but keyDataFieldLength less than sizeNeeded. Now I try to comment this code :

	/*if (sizeNeeded > *keyDataFieldLength) {
		      OPGP_ERROR_CREATE_ERROR(status, OPGP_ERROR_INSUFFICIENT_BUFFER, OPGP_stringify_error(OPGP_ERROR_INSUFFICIENT_BUFFER));
		      goto end;
	      }*/
      

> Can you please check if the JCShell output differs from gpshell (expect the different encrypted data because of the session key)?

I'm currently at home and forgot to bring the java card. I will reply to you next Monday. But I remember after I did a little modification as above, the key check value still different. the JCShell calculated 504A77, but the gpshell resulting in different value calculations. I will check again on Monday.

**Comment by koh-osug** [comment]
I have used the `putKeysSCP03.txt` with an Infineon and NXP card. I have to find time to rerun it next week. I have added your fix.

**Comment by yp25** [comment]
Hi Mr. @koh-osug ,

I have added AES keys successfully. What I did :

1.  Function calculate_key_check_value (crypto.c) needs to be modified to accept keyType parameter == GP211_KEY_TYPE_AES
```
OPGP_ERROR_STATUS calculate_key_check_value(GP211_SECURITY_INFO *secInfo,
	BYTE keyType,
	PBYTE keyData,
	DWORD keyDataLength,
	BYTE keyCheckValue[3]) {
	OPGP_ERROR_STATUS status;
	BYTE dummy[16];
	DWORD dummyLength;
	BYTE keyCheckTest[16];
	OPGP_LOG_START(_T("calculate_key_check_value"));
	memset(keyCheckTest, 0, 16);
	if (secInfo->secureChannelProtocol == GP211_SCP03 || keyType == GP211_KEY_TYPE_AES) {
		memset(keyCheckTest, 0x01, sizeof(keyCheckTest));
		status = calculate_enc_ecb_SCP03(keyData, keyDataLength, keyCheckTest, 16, dummy, &dummyLength);
	}
	else {
		status = calculate_enc_ecb_two_key_triple_des(keyData, keyCheckTest, 8, dummy, &dummyLength);
	}
	if (OPGP_ERROR_CHECK(status)) {
		goto end;
	}
	memcpy(keyCheckValue, dummy, 3);
	{ OPGP_ERROR_CREATE_NO_ERROR(status); goto end; }
end:
	OPGP_LOG_END(_T("calculate_key_check_value"), status);
	return status;
}
```
2.  Function get_key_data_field (crypto.c) also needs to be modified to accept keyType parameter == GP211_KEY_TYPE_AES 
```
OPGP_ERROR_STATUS get_key_data_field(GP211_SECURITY_INFO *secInfo,
							 PBYTE keyData,
							 DWORD keyDataLength,
							 BYTE keyType,
							 BYTE isSensitive,
							 PBYTE keyDataField,
							 PDWORD keyDataFieldLength,
							 BYTE keyCheckValue[3]) {
	OPGP_ERROR_STATUS status;
	DWORD sizeNeeded=0, i=0;
	BYTE encrypted_key[32];
	DWORD encrypted_key_length;
	BYTE keyCheckTest[16];
	OPGP_LOG_START(_T("get_key_data_field"));
	memset(keyCheckTest, 0, 16);
	// key type + length + key data + length + key check value
	sizeNeeded = 1 + 1 + keyDataLength + 1;
	if (secInfo->secureChannelProtocol == GP211_SCP03 || keyType == GP211_KEY_TYPE_AES) {
		// the length of the key component is always included
		sizeNeeded++;
	}
	if (isSensitive) {
		// 3 byte key check value
		sizeNeeded+=3;
	}	
	if (sizeNeeded > *keyDataFieldLength) {
		OPGP_ERROR_CREATE_ERROR(status, OPGP_ERROR_INSUFFICIENT_BUFFER, OPGP_stringify_error(OPGP_ERROR_INSUFFICIENT_BUFFER));
		goto end;
	}
	// set key type
	keyDataField[i++] = keyType;
	if (isSensitive) {
		status = encrypt_sensitive_data(secInfo, keyData, keyDataLength, encrypted_key, &encrypted_key_length);
		if (OPGP_ERROR_CHECK(status)) {
			goto end;
		}
		if (encrypted_key_length != keyDataLength || secInfo->secureChannelProtocol == GP211_SCP03 || keyType == GP211_KEY_TYPE_AES) {
			// + 1 byte key component length field
			keyDataField[i++] = encrypted_key_length + 1;
			keyDataField[i++] = keyDataLength;
		}
		else {
			// not padded and no length must be specified
			keyDataField[i++] = encrypted_key_length;
		}
		memcpy(keyDataField+i, encrypted_key, encrypted_key_length);
		i+= encrypted_key_length;
	}
	else {
		keyDataField[i++] = (BYTE)keyDataLength;
		// not sensitive - copy directly, no key component length is needed
		memcpy(keyDataField+i, keyData, keyDataLength);
		i+=keyDataLength;
	}
	// we always use key check values
	keyDataField[i++] = 0x03; // length of key check value
	status = calculate_key_check_value(secInfo, keyType, keyData, keyDataLength, keyCheckValue);
	if (OPGP_ERROR_CHECK(status)) {
		goto end;
	}
	memcpy(keyDataField+i, keyCheckValue, 3);
	i+=3;
	*keyDataFieldLength = i;
	{ OPGP_ERROR_CREATE_NO_ERROR(status); goto end; }
end:

	OPGP_LOG_END(_T("get_key_data_field"), status);
	return status;
}
```

with this modification, now put_key_sc works well 
```
put_sc_key -keyType 88 -keyver 0 -newkeyver 48 -mac_key 404142434445464748494A4B4C4D4E4F -enc_key 404142434445464748494A4B4C4D4E4F -kek_key 404142434445464748494A4B4C4D4E4F
Command --> 80D800814630881110B23034FA4329DE9AD8E91583618813B303504A77881110B23034FA4329DE9AD8E91583618813B303504A77881110B23034FA4329DE9AD8E91583618813B303504A7700
Wrapped command --> 80D800814630881110B23034FA4329DE9AD8E91583618813B303504A77881110B23034FA4329DE9AD8E91583618813B303504A77881110B23034FA4329DE9AD8E91583618813B303504A7700
Response <-- 30504A77504A77504A779000
Unwrapped response <-- 30504A77504A77504A779000
```

**Comment by koh-osug** [comment]
Awesome! I have to find out, when my SCP03 card were working without this. When I publish the next release so you want to be attributed? What name / email should I use then?

**Comment by koh-osug** [comment]
I have integrated your changes. Please check. I found the explanation also why it works in my case: I was using SCP03 as protocol, not SCP02 for putting a SCP03 key.

**Comment by yp25** [comment]
> Awesome! I have to find out, when my SCP03 card were working without this. When I publish the next release so you want to be attributed? What name / email should I use then?

Thank you for considering attribution in the next release. Please use yp25 / yudhipra25@gmail.com. 

> I have integrated your changes. Please check. I found the explanation also why it works in my case: I was using SCP03 as protocol, not SCP02 for putting a SCP03 key.

I have checked the latest commit - put_sc_with_key_type branch. please modify line 1427 crypto.c with || keyType == GP211_KEY_TYPE_AES)
```
if (encrypted_key_length != keyDataLength || secInfo->secureChannelProtocol == GP211_SCP03 || keyType == GP211_KEY_TYPE_AES)
```

without || keyType == GP211_KEY_TYPE_AES, will result error like this :
put_secure_channel_keys() returns 0x80304000 (A used buffer is too small.)

Thank you for your effort & hard work Mr. @koh-osug

**Comment by koh-osug** [comment]
Updated. Please also see the AUTHORS file in gpshell / globalplatform for the attribution.

**Comment by yp25** [comment]
Thank you Mr. @koh-osug
