### ISSUE TITLE
RSA exponent size incorrect in code comments

### ISSUE THREAD

**Issue by pspacek** [kaoh/globalplatform#87]
I believe this comment is incorrect:
https://github.com/kaoh/globalplatform/blob/1fe699635bdbe6773ebc458140b8791acc4493ac/globalplatform/src/crypto.c#L2080

The comment says `65337` (0xff39), but I think it meant the usual 65537 (0x10001). 65337 has small factors...

**Comment by kaoh** [comment]
Right, the comment seems to be wrong. Fixed now. Thanks.
